bypass-blocks: []
unbreakable-blocks: []
unprotectable-blocks: []
repairable-items: [256,257,258,259,267,268,269,270,271,272,273,274,275,276,277,278,279,283,284,285,286,290,291,292,293,294,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,359]
tool-items: [269,270,271,273,274,275,277,278,279,284,285,286,290,291,292,293,294]
force-field-blocks:
-   title: City Protection
    block: 57
    radius: 20
    custom-height: 15
    prevent-fire: true
    prevent-place: true
    prevent-destroy: true
    prevent-explosions: true
    prevent-unprotectable: true
    prevent-flow: true
    prevent-teleport: true
    welcome-message: true
    farewell-message: true
    can-change-owner: true
    enable-on-src: true
    mixing-group: 1
    cuboid: true
-   title: Town Protection Example
    block: 0
    radius: 1
    customVolume: 2000000
    prevent-fire: true
    prevent-place: true
    prevent-destroy: true
    prevent-explosions: true
    prevent-unprotectable: true
    prevent-flow: true
    prevent-teleport: true
    welcome-message: true
    farewell-message: true
    can-change-owner: true
    enable-on-src: true
    cuboid: true
    cuboid: true
-   title: Town SubPlot Example
    block: 0
    radius: 10
    custom-height: 21
    sub-plot: true
    allowed-only-inside: [Town Protection]
    prevent-fire: true
    prevent-place: true
    prevent-destroy: true
    prevent-explosions: true
    prevent-unprotectable: true
    prevent-flow: true
    prevent-teleport: true
    welcome-message: true
    farewell-message: true
    can-change-owner: true
    enable-on-src: true
-   title: Entry Bouncer
    block: 22
    radius: 5
    prevent-entry: true
    prevent-fire: true
    prevent-place: true
    prevent-destroy: true
    prevent-explosions: true
    prevent-unprotectable: true
    prevent-flow: true
    enable-on-src: true
    can-change-owner: true
    cuboid: true
-   title: Jack-o-Death
    block: 91
    radius: 5
    damage: 4
    no-conflict: true
    sneaking-bypass: true
    no-player-place: true
    mixing-group: 2
-   title: Creature Repeller
    block: 30
    radius: 20
    prevent-mob-spawn: true
    prevent-animal-spawn: true
    remove-mob: true
    no-conflict: true
    mixing-group: 1
    cuboid: true
-   title: Air of Atlantis
    block: 21
    radius: 10
    custom-height: 256
    air: true
    no-conflict: true
    mixing-group: 1
    cuboid: true
-   title: Proximity Snitch
    block: 25
    radius: 5
    snitch: true
    entry-alert: true
    no-conflict: true
    mixing-group: 2
    cuboid: true
-   title: The Shocker
    block: 97
    radius: 0
    custom-height: 3
    lightning: true
    lightning-replace-block: 0
    sneaking-bypass: true
    breakable: true
    no-conflict: true
    mixing-group: 2
    cuboid: true
-   title: Proximity Mine
    block: 73
    radius: 1
    custom-height: 5
    mine: true
    breakable: true
    sneaking-bypass: true
    mixing-group: 2
    no-conflict: true
-   title: Launch Pad
    block: 15
    radius: 1
    launch: true
    no-conflict: true
    sneaking-bypass: true
    custom-volume: 20
    mixing-group: 2
    cuboid: true
-   title: Sky Cannon
    block: 16
    radius: 0
    custom-height: 3
    custom-volume: 20
    sneaking-bypass: true
    cannon: true
    no-conflict: true
    mixing-group: 2
    cuboid: true
-   title: Grief Revert
    block: 41
    radius: 20
    custom-height: 15
    grief-revert: true
    welcome-message: true
    farewell-message: true
    enable-on-src: true
    mixing-group: 1
    cuboid: true
-   title: GodStone
    block: 99
    radius: 5
    heal: 4
    feed: 2
    repair: 25
    no-conflict: true
    mixing-group: 2
    cuboid: true
-   title: Forester
    block: 86
    radius: 20
    custom-height: 15
    forester: true
    ground-block: 2
    fertile-blocks: [1, 3, 12, 87, 88]
    tree-types: [0, 0, 0, 1, 1, 2, 3, 4, 4]
    shrub-types: [1, 1, 1, 2, 2, 3, 4]
    shrub-density: 64
    tree-count: 64
    grow-time: 10
    no-owner: true
    no-conflict: true
-   title: Peace Keeper
    block: 19
    radius: 10
    prevent-pvp: true
    no-player-place: true
    prevent-mob-damage: true
    cuboid: true
warn:
    slow-damage: true
    pvp: true
    instant-heal: true
    launch: true
    fast-damage: true
    use: true
    air: true
    slow-feeding: true
    fire: true
    cannon: true
    destroy-area: true
    destroy: true
    slow-heal: true
    entry: true
    unprotectable: true
    mine: true
    slow-repair: true
    place: true
cleanup:
    player-inactivity-purge-days: 45
    snitch-unused-purge-days: 30
settings:
    sneak-to-place-normal-block: true
    sneak-to-place-field: false
    show-debug-info: false
    show-default-welcome-farewell-messages: true
    dynmap-flags-disabled-by-default: true
    welcome-farewell-disabled-by-default: true
    disable-ground-info: false
    auto-download-vault: false
    global-field-limit: 1000000
    no-refund-for-fields: false
    off-by-default: false
    log-to-hawkeye: false
    lines-per-page: 12
    disable-bypass-alerts-for-admins: false
    disable-alerts-for-admins: true
    public-block-details: false
    blacklisted-worlds: [creative_world]
    drop-on-delete: true
log:
    bypass-pvp: true
    pvp: true
    bypass-destroy: true
    use: true
    fire: true
    destroy: true
    destroy-area: false
    place-area: false
    entry: true
    unprotectable: true
    bypass-place: true
    place: true
    rollback: true
    bypass-delete: true
    conflict-place: true
cuboid:
    visualization-blocktype: 20
    defining-blocktype: 49
visualization:
    block-type: 20
    seconds: 30
    mark-block-type: 49
    end-on-player-move: false
    frame-block-type: 20
    blocks-to-send: 100
    ticks-between-sends: 10
    default-density: 8
    max-fields-to-visualize-at-once: 5
notify:
    destroy: true
    bypass-pvp: true
    bypass-destroy: true
    bypass-unprotectable: true
    bypass-place: true
    place: true
    rollback: true
    fly-zones: true
grief-undo:
    min-interval-secs: 30
    black-list:
    - 92
saving:
    frequency-seconds: 15
    max-records-per-snitch: 50
mysql:
    username: ''
    host: localhost
    enable: false
    password: ''
    database: minecraft
    port: 3306